---
kind: pipeline
name: python-3-7
type: docker
platform:
  os: linux
  arch: amd64

steps:
- name: test-3-7
  image: python:3.7
  environment:
    TOX_WORK_DIR: /tmp/.tox
    HAS_COVERALLS: true
    COVERALLS_SERVICE_NAME: PySHACL-Drone
    COVERALLS_REPO_TOKEN:
      from_secret: coveralls_token
  volumes:
    - name: tox_cache
      path: /tmp/.tox
  commands:
  - pip3 install --upgrade tox
  - tox -e py37

volumes:
- name: tox_cache
  temp: {}

---
kind: pipeline
name: python-3-8
type: docker
platform:
  os: linux
  arch: amd64

steps:
- name: test-3-8
  image: python:3.8
  environment:
    TOX_WORK_DIR: /tmp/.tox
  volumes:
    - name: tox_cache
      path: /tmp/.tox
  commands:
  - pip3 install --upgrade tox
  - tox -e py38
- name: type-checking-3-8
  image: python:3.8
  environment:
    TOX_WORK_DIR: /tmp/.tox
  volumes:
    - name: tox_cache
      path: /tmp/.tox
  commands:
  - pip3 install --upgrade tox
  - tox -e type-checking
- name: lint-3-8
  image: python:3.8
  environment:
    TOX_WORK_DIR: /tmp/.tox
  volumes:
    - name: tox_cache
      path: /tmp/.tox
  commands:
  - pip3 install --upgrade tox
  - tox -e lint
#- name: security
#  image: snyk/snyk:python-3.8
#  environment:
#    SNYK_TOKEN:
#      from_secret: snyk_token
#    PROJECT_PATH: /drone/src
#  commands:
#  - snyk --org=ashleysommer test
#  - snyk code --org=ashleysommer test

volumes:
- name: tox_cache
  temp: {}

---
kind: pipeline
name: python-3-9
type: docker
platform:
  os: linux
  arch: amd64

steps:
- name: test-3-9
  image: python:3.9
  environment:
    TOX_WORK_DIR: /tmp/.tox
  volumes:
    - name: tox_cache
      path: /tmp/.tox
  commands:
  - pip3 install -U "pip>=21.0"
  - pip3 install --upgrade tox
  - tox -e py39

---
kind: pipeline
name: python-3-10
type: docker
platform:
  os: linux
  arch: amd64

steps:
- name: test-3-10
  image: python:3.10
  environment:
    TOX_WORK_DIR: /tmp/.tox
  volumes:
    - name: tox_cache
      path: /tmp/.tox
  commands:
  - pip3 install -U "pip>=21.3"
  - pip3 install --upgrade tox
  - tox -e py310
- name: type-checking-3-10
  image: python:3.10
  environment:
    TOX_WORK_DIR: /tmp/.tox
  volumes:
    - name: tox_cache
      path: /tmp/.tox
  commands:
  - pip3 install --upgrade tox
  - tox -e type-checking
- name: lint-3-10
  image: python:3.10
  environment:
    TOX_WORK_DIR: /tmp/.tox
  volumes:
    - name: tox_cache
      path: /tmp/.tox
  commands:
  - pip3 install --upgrade tox
  - tox -e lint

volumes:
- name: tox_cache
  temp: {}
